### ISSUE TITLE
The Website Template is not defined as an template.

### ISSUE THREAD

**Issue by CayoSkits** [lx78WyY0J5/Template-Website#1]
Bonjour.
J'ai dû télécharger l'intégralité du zip pour
Depuis le site Web. Regle-le, s'il te plait.

En allant dans Paramètres > Général. En bas du nom, cliquez sur _Template deposit_
Merci, CayoSkits.

**Comment by lx78WyY0J5** [comment]
Si j'ai bien compris tu souhaite faire passer ce repository en mode "template" ? 
Tandis qu'il est composé que de deux fichiers, et que le site est si moche que l'utiliser serait une blague 🤔 

~~Je vais plus tôt le supprimer, je sais même pas pourquoi j'ai gardé un template aussi moche dans mes repos 🤣~~

J'ai passé le repository en mode template, mais merci de ne pas l'utiliser, d'autres template son mieux pour démarrer
Ce template ne sert que à montrer comment utiliser Github page et ne devrait donc pas être utiliser pour autre chose que juste tester
